### ISSUE TITLE
korean//set-cjk-fonts 함수에러

### ISSUE THREAD

**Issue by lazysquid** [pA0k/spacemacs-korean#1]
안녕하세요. 
spacemacs-korean layer를 사용하려고 하다 문제가 생겨 이슈를 남깁니다.

레이어 설치는 .spacemacs.d/layers/korean 에 설치되어 있습니다.
스페이스맥스가 로드를 시도하는듯 하나 다음과 같은 오류 때문에 레이어를 사용할 수 없습니다.

```
progn: Symbol’s function definition is void: korean//set-cjk-fonts
```
`zh-hanja` 라는 매크로에서 에러가 나는데 자세한 내용은 잘 모르겠네요.

우분투 16.04, 스페이스맥스 버전은 0.200.9 를 사용중이고, 이맥스는 현재 26.0.50 버전을 사용중입니다.

**Comment by pA0k** [comment]
무신경하게 지내는 동안 Spacemacs 파일 적재 우선 순위가 바뀐 듯 하네요.
우선 동작하게는 만들어 두었습니다.
